#ifndef WOE_INPUT_STATE_ENUM_H
#define WOE_INPUT_STATE_ENUM_H

enum InputState
{
	WOE_INVALID_INPUT_STATE = -1,

	WOE_INPUT_STATE_DOWN,
	WOE_INPUT_STATE_UP,

	WOE_NUM_INPUT_STATES
};

#endif // WOE_INPUT_STATE_ENUM_H