#ifndef WOE_MOUSE_BUTTON_ENUM_H
#define WOE_MOUSE_BUTTON_ENUM_H

enum MouseButton
{
	WOE_INVALID_MOUSE_BUTTON = -1,

	WOE_MOUSE_BUTTON_LEFT,
	WOE_MOUSE_BUTTON_RIGHT,
	WOE_MOUSE_BUTTON_MIDDLE,

	WOE_NUM_MOUSE_BUTTONS
};

#endif // WOE_MOUSE_BUTTON_ENUM_H