#ifndef WOE_PRIMITIVE_TYPES_H
#define WOE_PRIMITIVE_TYPES_H

enum PrimitiveTypes
{
	WOE_INVALID_PRIMITIVE_TYPE = -1,
	
	WOE_PRIMITIVE_TYPE_TRIANGLE,
	WOE_PRIMITIVE_TYPE_TRIANGLE_STRIP,
	WOE_PRIMITIVE_TYPE_QUAD,

	WOE_NUM_PRIMITIVE_TYPES
};

#endif // WOE_PRIMITIVE_TYPES_H