#ifndef WOE_SCROLL_WHEEL_DIR_ENUM_H
#define WOE_SCROLL_WHEEL_DIR_ENUM_H

enum ScrollWheelDir
{
	WOE_INVALID_SCROLL_WHEEL_DIR = -1,

	WOE_SCROLL_WHEEL_DIR_UP,
	WOE_SCROLL_WHEEL_DIR_DOWN,
	WOE_SCROLL_WHEEL_DIR_LEFT,
	WOE_SCROLL_WHEEL_DIR_RIGHT,

	WOE_NUM_SCROLL_WHEEL_DIRS
};

#endif // WOE_SCROLL_WHEEL_DIR_ENUM_H