#ifndef WOE_SHADER_TYPES_H
#define WOE_SHADER_TYPES_H

enum ShaderTypes
{
	WOE_INVALID_SHADER_TYPE = -1,
	WOE_SHADER_TYPE_VERTEX,
	WOE_SHADER_TYPE_FRAGMENT,
	WOE_SHADER_TYPE_PIXEL = WOE_SHADER_TYPE_FRAGMENT,
	WOE_NUM_SHADER_TYPES
};

#endif // WOE_SHADER_TYPES_H